name: atcs-practical
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - ipykernel=5.3.4
  - ipython=7.22.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - pip=21.0.1
  - python=3.8.8
  - conda-forge::cudatoolkit=11.1.1
  - pytorch=1.8.11 
  - pytorch::torchvision 
  - torchaudio  
  - pip:
    - sklearn
    - numpy==1.20.2
    - pytorch-lightning==1.2.7 
    - tqdm==4.60.0
    - wandb
    - spacy
    
